"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const path=require("node:path");
const root=path.resolve(__dirname,"..");const extensionRoot=path.join(root,"browser-extension","go-browser-local-observer-v1");const manifestPath=path.join(extensionRoot,"manifest.json");const contentPath=path.join(extensionRoot,"content-script.js");const panelPath=path.join(extensionRoot,"observer-panel.js");const backgroundPath=path.join(extensionRoot,"background.js");const builderPath=path.join(root,"scripts","build-go-browser-observer-extension.mjs");
function requireFile(file,message){assert.equal(fs.existsSync(file),true,message)}function source(){return[contentPath,panelPath,backgroundPath].map(file=>fs.readFileSync(file,"utf8")).join("\n")}
test("Observer is a separate Firefox Android extension with Gumroad-only host scope",()=>{requireFile(manifestPath,"Observer manifest is not implemented yet");const manifest=JSON.parse(fs.readFileSync(manifestPath,"utf8"));const matches=["*://gumroad.com/*","*://*.gumroad.com/*"];assert.equal(manifest.manifest_version,3);assert.equal(manifest.name,"GO Browser Local Observer Eye");assert.equal(manifest.browser_specific_settings.gecko.id,"go-browser-local-observer-v1@pureekangraw.local");assert.deepEqual(manifest.browser_specific_settings.gecko_android,{});assert.deepEqual([...manifest.content_scripts[0].matches].sort(),[...matches].sort());assert.equal(JSON.stringify(manifest).includes("<all_urls>"),false);assert.equal(JSON.stringify(manifest).includes("go-browser-local-v1@pureekangraw.local"),false)});
test("Observer permission set is minimal and screenshot uses activeTab only",()=>{const manifest=JSON.parse(fs.readFileSync(manifestPath,"utf8"));assert.deepEqual(manifest.permissions||[],["activeTab"]);for(const forbidden of ["tabs","cookies","history","webRequest","clipboardRead","clipboardWrite","storage","scripting"])assert.equal((manifest.permissions||[]).includes(forbidden),false)});
test("Observer package never imports Safe Fill and contains no page action primitive",()=>{for(const file of [contentPath,panelPath,backgroundPath])requireFile(file,`missing Observer file: ${path.basename(file)}`);const combined=source();assert.equal(combined.includes("go-browser-safe-fill"),false);assert.equal(combined.includes("go-browser-panel"),false);assert.equal(/\.click\s*\(/.test(combined),false);assert.equal(/\.submit\s*\(/.test(combined),false);assert.equal(/new\s+Function\s*\(/.test(combined),false);assert.equal(/\beval\s*\(/.test(combined),false);assert.equal(/clipboard|document\.cookie|localStorage|sessionStorage/.test(combined),false)});
test("Observer UI exposes explicit start stop observe and one-shot screenshot controls",()=>{const panel=fs.readFileSync(panelPath,"utf8");for(const label of ["Start Observer","Stop Observer","Observe now","One screenshot"])assert.equal(panel.includes(label),true);for(const state of ["OFF","OBSERVING","EXPIRED"])assert.equal(panel.includes(state),true)});
test("background screenshot bridge is one request to one capture and otherwise fail-closed",()=>{const background=fs.readFileSync(backgroundPath,"utf8");assert.match(background,/captureVisibleTab/);assert.match(background,/SCREENSHOT_CONSENT_REQUIRED/);assert.match(background,/SENSITIVE_CONTENT_BLOCKED/);assert.equal(background.includes("setInterval"),false);assert.equal(background.includes("setTimeout"),false)});
test("Observer has a dedicated builder instead of changing Safe Fill build source",()=>{requireFile(builderPath,"Observer builder is not implemented yet");const builder=fs.readFileSync(builderPath,"utf8");assert.equal(builder.includes("go-browser-local-observer-v1"),true);assert.equal(builder.includes("go-browser-local-v1"),false)});
