"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const path=require("node:path");
const root=path.resolve(__dirname,"..");const dispatcherPath=path.join(root,".github","workflows","go-browser-extension-sign.yml");const configPath=path.join(root,"wrangler.go-hub-observer-reality.jsonc");
function read(file){assert.equal(fs.existsSync(file),true,`missing ${path.basename(file)}`);return fs.readFileSync(file,"utf8")}
test("existing default-branch manual workflow dispatches Observer Reality Package on Observer branches",()=>{const workflow=read(dispatcherPath);assert.match(workflow,/name:\s*GO Browser Extension Sign/);assert.match(workflow,/workflow_dispatch:/);assert.match(workflow,/startsWith\(github\.ref_name, 'feat\/go-browser-local-observer-eye-v1'\)/);assert.match(workflow,/observer-reality-package:/);assert.match(workflow,/safe-fill-sign:/)});
test("Safe Fill manual signing path remains available outside Observer branches",()=>{const workflow=read(dispatcherPath);for(const marker of["build:go-browser-extension","dist/go-browser-local-v1","go-browser-local-v1-unsigned.xpi","go-browser-local-v1-signed-${{ github.sha }}"])assert.equal(workflow.includes(marker),true,`missing Safe Fill marker: ${marker}`)});
test("Observer Reality path is manual-only and never merges or deploys production GO Hub",()=>{const workflow=read(dispatcherPath);assert.doesNotMatch(workflow,/\n\s*pull_request:/);assert.doesNotMatch(workflow,/\n\s*push:/);assert.doesNotMatch(workflow,/go_hub_merge|gh\s+pr\s+merge|wrangler\.go-hub\.jsonc/);assert.match(workflow,/wrangler\.go-hub-observer-reality\.jsonc/)});
test("Reality Worker is an isolated workers.dev Observer endpoint with only Observer session DO",()=>{const config=JSON.parse(read(configPath));assert.equal(config.name,"go-hub-eye-reality");assert.equal(config.main,"go-hub-edge-worker.mjs");assert.equal(config.workers_dev,true);assert.deepEqual(config.durable_objects.bindings,[{name:"OBSERVER_SESSIONS",class_name:"ObserverSessionRegistry"}]);assert.equal(JSON.stringify(config).includes("HEPHAESTUS"),false);assert.deepEqual(config.vars.BROWSER_POLICY,{allowedHostnames:["gumroad.com","*.gumroad.com"],requireOwnerPasscode:true})});
test("Observer Reality path gates source, deploys isolated Hub, signs Observer, hashes XPI, and emits manifest",()=>{const workflow=read(dispatcherPath);for(const marker of["npm run deploy:gate","CLOUDFLARE_API_TOKEN","CLOUDFLARE_ACCOUNT_ID","GOHUB_OWNER_PASSCODE","AMO_SIGN_KEY","AMO_SIGN_SECRET","accounts/${CLOUDFLARE_ACCOUNT_ID}/workers/subdomain","go-hub-eye-reality","/hub/observer","build:go-browser-observer-extension","kewisch/action-web-ext@84a13bb9e1b6108c43788ba091c41ca1dba6ad45","channel: unlisted","sha256sum","observer-reality-manifest.json","github.sha","actions/upload-artifact@v4"])assert.equal(workflow.includes(marker),true,`missing reality marker: ${marker}`)});
test("Reality artifact keeps signed XPI and manifest together for owner handoff",()=>{const workflow=read(dispatcherPath);assert.match(workflow,/go-browser-observer-reality-\$\{\{ github\.sha \}\}/);assert.match(workflow,/observer-reality-manifest\.json/);assert.match(workflow,/\$\{\{ steps\.observer_sign\.outputs\.target \}\}/)});
