"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const path=require("node:path");const{pathToFileURL}=require("node:url");
const root=path.resolve(__dirname,"..");const observerPath=path.join(root,"go-browser-local-observer.js");const observerUrl=pathToFileURL(observerPath).href;
async function load(tag){assert.equal(fs.existsSync(observerPath),true,"Observer runtime is not implemented yet");return import(`${observerUrl}?observer=${tag}-${Date.now()}`)}
function control({tagName="INPUT",type="text",label="",value="",checked=false,hidden=false,contenteditable=false,autocomplete="",name="",width=100,height=20}={}){const attributes=new Map();if(label)attributes.set("aria-label",label);if(contenteditable)attributes.set("contenteditable","true");if(autocomplete)attributes.set("autocomplete",autocomplete);if(name)attributes.set("name",name);return{tagName,type,value,textContent:contenteditable?value:"",checked,hidden,disabled:false,readOnly:false,required:false,labels:[],options:[],getAttribute(key){return attributes.has(key)?attributes.get(key):null},getBoundingClientRect(){return{width,height,top:0,left:0,bottom:height,right:width}}}}
function documentWith(controls,title="Gumroad product"){return{title,querySelectorAll(selector){assert.match(selector,/input/);return controls},getElementById(){return null}}}
function activeSession(observer,overrides={}){return observer.createObserverSession({sessionId:"session-1",startedAt:1000,ttlMs:60000,origin:"https://gumroad.com",...overrides})}
function collect(observer,{controls=[],session=activeSession(observer),now=2000,href="https://gumroad.com/products/demo?token=secret#frag"}={}){return observer.collectObserverSnapshot({document:documentWith(controls),location:new URL(href),title:"Edit product",viewport:{width:390,height:844},session,now})}
function bootstrap(overrides={}){return{ok:true,session_id:"session-1",session_token:"token-1",expires_at:Date.now()+600000,allowed_origin:"https://gumroad.com",hub_origin:"https://hub.example",...overrides}}
test("no active owner session blocks evidence",async()=>{const o=await load("inactive");assert.deepEqual(collect(o,{session:null}),{ok:false,code:"SESSION_INACTIVE"})});
test("expired session blocks evidence",async()=>{const o=await load("expired");assert.deepEqual(collect(o,{session:activeSession(o,{startedAt:1000,ttlMs:500}),now:2000}),{ok:false,code:"SESSION_EXPIRED"})});
test("host outside Gumroad allowlist is blocked",async()=>{const o=await load("host");assert.deepEqual(collect(o,{href:"https://example.com/product"}),{ok:false,code:"HOST_BLOCKED"})});
test("query string and fragment never leave the local observer",async()=>{const o=await load("path"),r=collect(o);assert.equal(r.ok,true);assert.equal(r.packet.origin,"https://gumroad.com");assert.equal(r.packet.sanitized_path,"/products/demo");assert.equal(JSON.stringify(r.packet).includes("token=secret"),false);assert.equal(JSON.stringify(r.packet).includes("frag"),false)});
test("password OTP payment token hidden and file values never appear in output",async()=>{const o=await load("sensitive"),controls=[control({type:"password",label:"Password",value:"pw-secret"}),control({label:"Verification code",autocomplete:"one-time-code",value:"123456"}),control({label:"Card number",autocomplete:"cc-number",value:"4111111111111111"}),control({label:"Access token",value:"tok-secret"}),control({type:"hidden",label:"Hidden",value:"hidden-secret",hidden:true}),control({type:"file",label:"Upload",value:"/private/file.txt"})],serialized=JSON.stringify(collect(o,{controls}).packet);for(const secret of["pw-secret","123456","4111111111111111","tok-secret","hidden-secret","/private/file.txt"])assert.equal(serialized.includes(secret),false)});
test("unknown fields export metadata only with UNKNOWN_REDACTED",async()=>{const o=await load("unknown"),r=collect(o,{controls:[control({label:"Mystery",value:"must-not-leak"})]});assert.equal(r.packet.fields[0].safe_value_or_state,"UNKNOWN_REDACTED");assert.equal(r.packet.fields[0].sensitivity,"unknown");assert.equal(JSON.stringify(r.packet).includes("must-not-leak"),false)});
test("Gumroad fixture reads Name Description Price and visible boolean state",async()=>{const o=await load("gumroad"),r=collect(o,{controls:[control({label:"Name",name:"name",value:"Lost Era"}),control({tagName:"DIV",label:"Description",value:"Reality fracture",contenteditable:true}),control({type:"number",label:"Price",value:"9"}),control({type:"checkbox",label:"Published",checked:true})]}),fields=Object.fromEntries(r.packet.fields.map(field=>[field.label,field]));assert.equal(fields.Name.safe_value_or_state,"Lost Era");assert.equal(fields.Description.safe_value_or_state,"Reality fracture");assert.equal(fields.Price.safe_value_or_state,"9");assert.equal(fields.Published.safe_value_or_state,true)});
test("zero-size or hidden controls are omitted",async()=>{const o=await load("visible"),r=collect(o,{controls:[control({label:"Name",value:"Visible"}),control({label:"Description",value:"Invisible",width:0,height:0}),control({label:"Price",value:"99",hidden:true})]});assert.deepEqual(r.packet.fields.map(field=>field.label),["Name"])});
test("stopping a session blocks transmission immediately",async()=>{const o=await load("stop");assert.deepEqual(collect(o,{session:o.stopObserverSession(activeSession(o))}),{ok:false,code:"SESSION_INACTIVE"})});
test("screenshot consent is one-shot and requires an active session",async()=>{const o=await load("screenshot"),session=activeSession(o),without=o.consumeScreenshotConsent(session,2000);assert.equal(without.code,"SCREENSHOT_CONSENT_REQUIRED");const first=o.consumeScreenshotConsent(o.grantScreenshotConsent(session,2000),2001);assert.equal(first.allowed,true);assert.equal(o.consumeScreenshotConsent(first.session,2002).code,"SCREENSHOT_CONSENT_REQUIRED")});
test("bootstrap is short lived, HTTPS-only, and Gumroad-bound",async()=>{const o=await load("bootstrap");const parsed=o.parseObserverBootstrap(JSON.stringify(bootstrap()),2000);assert.equal(parsed.hubOrigin,"https://hub.example");assert.equal(parsed.sessionId,"session-1");assert.equal(parsed.allowedOrigin,"https://gumroad.com");assert.throws(()=>o.parseObserverBootstrap(bootstrap({expires_at:1000}),2000),/SESSION_EXPIRED/);assert.throws(()=>o.parseObserverBootstrap(bootstrap({hub_origin:"http://hub.example"}),2000),/DESTINATION_BLOCKED/);assert.throws(()=>o.parseObserverBootstrap(bootstrap({allowed_origin:"https://evil.example"}),2000),/HOST_BLOCKED/)});
test("transport is fixed to GO Hub and blocks any other destination",async()=>{const o=await load("destination"),sent=[];const transport=o.createObserverTransport({bootstrap:bootstrap(),fetchImpl:async(url,init)=>{sent.push({url,init});return new Response("{}",{status:200})}});assert.deepEqual(await transport.send({destination:"https://evil.example/collect",packet:{}}),{ok:false,code:"DESTINATION_BLOCKED"});assert.equal(sent.length,0)});
test("Hub network failure returns HUB_UNAVAILABLE without fallback",async()=>{const o=await load("hub-down");let calls=0;const transport=o.createObserverTransport({bootstrap:bootstrap(),fetchImpl:async()=>{calls+=1;throw new Error("offline")}});assert.deepEqual(await transport.sendSnapshot({}),{ok:false,code:"HUB_UNAVAILABLE"});assert.equal(calls,1)});
test("Observer public API contains no action primitive",async()=>{const o=await load("api"),forbidden=/click|type|fill|submit|publish|purchase|navigate|eval/i;assert.deepEqual(Object.keys(o).filter(key=>forbidden.test(key)),[])});
