"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const path=require("node:path");const{pathToFileURL}=require("node:url");
const root=path.resolve(__dirname,"..");const observerUrl=pathToFileURL(path.join(root,"go-browser-local-observer.js")).href;const sessionUrl=pathToFileURL(path.join(root,"go-hub-browser-observer-session.js")).href;const workerUrl=pathToFileURL(path.join(root,"go-hub-edge-worker.mjs")).href;
class MemoryStorage{constructor(){this.map=new Map()}async get(k){return this.map.get(k)}async put(k,v){this.map.set(k,v)}}
async function modules(tag){return{observer:await import(`${observerUrl}?shot=${tag}-${Date.now()}`),session:await import(`${sessionUrl}?shot=${tag}-${Date.now()}`),worker:await import(`${workerUrl}?shot=${tag}-${Date.now()}`)}}
function bootstrap(){return{session_id:"session-1",session_token:"token-1",expires_at:Date.now()+600000,allowed_origin:"https://gumroad.com",hub_origin:"https://hub.example"}}
function packet(ref=null){return{schema_version:"go-browser-observer-v1",session_id:"session-1",captured_at:new Date(2500).toISOString(),origin:"https://gumroad.com",sanitized_path:"/products/demo",page_title:"Edit product",viewport:{width:390,height:844},page_fingerprint:"obsfp:abc12345",visible_landmarks:[],visible_text_snippets:[],interactive_elements:[],fields:[],redaction_report:{sensitive_blocked:0,unknown_redacted:0,hidden_omitted:0},optional_screenshot_ref:ref}}
test("screenshot safety fails closed on redacted fields, suspicious text, or opaque visual surfaces",async()=>{const{observer}=await modules("guard");const cleanDoc={body:{innerText:"Edit product Name Description Price"},querySelectorAll(){return[]}};assert.deepEqual(observer.assessScreenshotSafety({document:cleanDoc,snapshot:packet()}),{safe:true,code:null});assert.deepEqual(observer.assessScreenshotSafety({document:cleanDoc,snapshot:{...packet(),redaction_report:{sensitive_blocked:1,unknown_redacted:0,hidden_omitted:0}}}),{safe:false,code:"SENSITIVE_CONTENT_BLOCKED"});assert.equal(observer.assessScreenshotSafety({document:{body:{innerText:"Access token sk-secret"},querySelectorAll(){return[]}},snapshot:packet()}).safe,false);assert.equal(observer.assessScreenshotSafety({document:{body:{innerText:"safe"},querySelectorAll(selector){return selector.includes("iframe")?[{hidden:false,getBoundingClientRect(){return{width:100,height:100}}}]:[]}},snapshot:packet()}).safe,false)});
test("transport uploads at most one guarded image to the fixed Hub screenshot endpoint",async()=>{const{observer}=await modules("transport");const calls=[];const transport=observer.createObserverTransport({bootstrap:bootstrap(),fetchImpl:async(url,init)=>{calls.push({url,init});return new Response(JSON.stringify({ok:true,screenshot_ref:"shot:1"}),{status:200,headers:{"content-type":"application/json"}})}});const result=await transport.uploadScreenshot({dataUrl:"data:image/jpeg;base64,AA==",pageFingerprint:"obsfp:abc12345"});assert.equal(result.ok,true);assert.equal(result.screenshot_ref,"shot:1");assert.equal(calls.length,1);assert.equal(calls[0].url,"https://hub.example/hub/api/browser/observer/screenshot")});
test("server screenshot store consumes consent once and binds screenshot to current fingerprint",async()=>{const{session}=await modules("store");const storage=new MemoryStorage();const service=session.createObserverSessionService({storage,now:()=>2500,randomUUID:()=>"session-1",randomToken:()=>"token-1"});await service.start({allowedOrigin:"https://gumroad.com",ttlMs:600000});assert.equal((await service.acceptSnapshot({sessionId:"session-1",sessionToken:"token-1",packet:packet()})).ok,true);assert.equal((await service.grantScreenshot({sessionId:"session-1",sessionToken:"token-1"})).ok,true);const stored=await service.storeScreenshot({sessionId:"session-1",sessionToken:"token-1",dataUrl:"data:image/jpeg;base64,AA==",pageFingerprint:"obsfp:abc12345"});assert.equal(stored.ok,true);assert.match(stored.screenshot_ref,/^shot:/);assert.deepEqual(await service.storeScreenshot({sessionId:"session-1",sessionToken:"token-1",dataUrl:"data:image/jpeg;base64,AA==",pageFingerprint:"obsfp:abc12345"}),{ok:false,code:"SCREENSHOT_CONSENT_REQUIRED"});const accepted=await service.acceptSnapshot({sessionId:"session-1",sessionToken:"token-1",packet:packet(stored.screenshot_ref)});assert.equal(accepted.ok,true);const latest=await service.latest();assert.equal(latest.latest.optional_screenshot_ref,stored.screenshot_ref)});
test("Hub screenshot upload route is session-bound and never touches Browser Run",async()=>{const{worker}=await modules("worker");let browserCalled=false;const calls=[];const sessions={async storeScreenshot(input){calls.push(input);return{ok:true,screenshot_ref:"shot:1"}}};const handler=worker.createEdgeWorkerHandler({delegate:{async fetch(){return new Response("delegated")}},factoryMcp:{async fetch(){return new Response("mcp")}},observerSessions:sessions});const response=await handler.fetch(new Request("https://hub.example/hub/api/browser/observer/screenshot",{method:"POST",headers:{"content-type":"application/json","origin":"https://gumroad.com","x-go-observer-session-id":"session-1","x-go-observer-session-token":"token-1"},body:JSON.stringify({data_url:"data:image/jpeg;base64,AA==",page_fingerprint:"obsfp:abc12345"})}),{BROWSER:{async quickAction(){browserCalled=true}},BROWSER_POLICY:{allowedHostnames:["gumroad.com","*.gumroad.com"],requireOwnerPasscode:true}});assert.equal(response.status,200);assert.equal(browserCalled,false);assert.equal((await response.json()).screenshot_ref,"shot:1");assert.equal(calls.length,1)});
