"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const path=require("node:path");const {pathToFileURL}=require("node:url");const root=path.resolve(__dirname,"..");
test("each decision concern has exactly one authority",async()=>{const m=await import(pathToFileURL(path.join(root,"go-hub-authority-map.js")).href);const owners=m.assertUniqueDecisionAuthority();assert.equal(owners.EVIDENCE_GATE,"heimdall");assert.equal(owners.WORK_IDENTITY,"centre");assert.equal(owners.PRODUCTION,"factory");assert.equal(owners.KNOWLEDGE_EXCHANGE,"counter");assert.equal(owners.AUDIT_HISTORY,"audit");assert.equal(owners.HEALTH_CLASSIFICATION,"maintenance");});
test("Heimdall is the only Hub evidence decision gate and consumes checker results",async()=>{const h=await import(pathToFileURL(path.join(root,"go-hub-heimdall.js")).href);assert.equal(h.decideEvidenceGate({workId:"W",checkpointId:"C",checks:[{id:"piece-qc",status:"PASS",evidenceRef:"ev://1"},{id:"readback",status:"PASS",evidenceRef:"ev://2"}]}).decision,"PASS");assert.equal(h.decideEvidenceGate({workId:"W",checkpointId:"C",checks:[{id:"assembly-qc",status:"FAIL"}]}).decision,"REJECT");assert.equal(h.decideEvidenceGate({workId:"W",checkpointId:"C",checks:[]}).decision,"WAIT");});
test("Audit Sentinel emits an audit event but does not store or approve it",async()=>{const h=await import(pathToFileURL(path.join(root,"go-hub-heimdall.js")).href);const d=h.decideEvidenceGate({workId:"W",checkpointId:"C",checks:[{id:"qc",status:"PASS",evidenceRef:"ev://1"}]});const e=h.auditSentinelEvent(d,{eventId:"EV-H",targetId:"go-hub"});assert.equal(e.type,"HEIMDALL_GATE_DECISION");assert.equal(e.details.decision,"PASS");assert.equal(Object.hasOwn(e,"sequence"),false);});

test("Factory QC remains a checker and cannot own the Hub Evidence Gate",async()=>{const m=await import(pathToFileURL(path.join(root,"go-hub-authority-map.js")).href);const map=m.authorityMap();assert.ok(map.factory.checks.includes("PIECE_QC"));assert.ok(map.factory.checks.includes("ASSEMBLY_QC"));assert.equal(map.factory.decisionAuthority.includes("EVIDENCE_GATE"),false);});
test("Centre owns identity/distribution but not evidence acceptance",async()=>{const m=await import(pathToFileURL(path.join(root,"go-hub-authority-map.js")).href);const map=m.authorityMap();assert.ok(map.centre.decisionAuthority.includes("WORK_IDENTITY"));assert.ok(map.centre.decisionAuthority.includes("DISTRIBUTION"));assert.equal(map.centre.decisionAuthority.includes("EVIDENCE_GATE"),false);});
test("Knowledge and Audit boundaries cannot silently become Evidence Gate",async()=>{const m=await import(pathToFileURL(path.join(root,"go-hub-authority-map.js")).href);const map=m.authorityMap();assert.equal(map.counter.decisionAuthority.includes("EVIDENCE_GATE"),false);assert.equal(map.audit.decisionAuthority.includes("EVIDENCE_GATE"),false);assert.equal(map.maintenance.decisionAuthority.includes("EVIDENCE_GATE"),false);});

test("Heimdall preserves pending checker state instead of misclassifying it as rejection",async()=>{const h=await import(pathToFileURL(path.join(root,"go-hub-heimdall.js")).href+"?wait="+Date.now());const d=h.decideEvidenceGate({workId:"W",checkpointId:"C",checks:[{id:"qc",status:"WAIT"}]});assert.equal(d.decision,"WAIT");assert.equal(d.reason,"EVIDENCE_CHECK_PENDING");});
test("Audit Sentinel fails closed without durable event identity or work identity",async()=>{const h=await import(pathToFileURL(path.join(root,"go-hub-heimdall.js")).href+"?audit="+Date.now());assert.throws(()=>h.auditSentinelEvent({decision:"PASS",workId:"W",checkpointId:"C"},{}),/EVENT_ID_REQUIRED/);assert.throws(()=>h.auditSentinelEvent({decision:"PASS"},{eventId:"EV"}),/WORK_IDENTITY_REQUIRED/);});
