"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const path=require("node:path");const{pathToFileURL}=require("node:url");
const root=path.resolve(__dirname,"..");const modulePath=path.join(root,"go-hub-browser-observer-session.js");const moduleUrl=pathToFileURL(modulePath).href;
class MemoryStorage{constructor(){this.map=new Map()}async get(k){return this.map.get(k)}async put(k,v){this.map.set(k,v)}async delete(k){this.map.delete(k)}}
async function load(tag){assert.equal(fs.existsSync(modulePath),true,"Observer session service is not implemented yet");return import(`${moduleUrl}?session=${tag}-${Date.now()}`)}
function packet(overrides={}){return{schema_version:"go-browser-observer-v1",session_id:"session-1",captured_at:new Date(2000).toISOString(),origin:"https://gumroad.com",sanitized_path:"/products/demo",page_title:"Edit product",viewport:{width:390,height:844},page_fingerprint:"obsfp:abc12345",visible_landmarks:[],visible_text_snippets:[],interactive_elements:[],fields:[],redaction_report:{sensitive_blocked:0,unknown_redacted:0,hidden_omitted:0},optional_screenshot_ref:null,...overrides}}
test("owner-started session is server-issued, short lived, and secret-backed",async()=>{const m=await load("start");const storage=new MemoryStorage();const service=m.createObserverSessionService({storage,now:()=>1000,randomUUID:()=>"session-1",randomToken:()=>"token-1"});const started=await service.start({allowedOrigin:"https://gumroad.com",ttlMs:600000});assert.deepEqual(started,{ok:true,session_id:"session-1",session_token:"token-1",expires_at:601000,allowed_origin:"https://gumroad.com"});const stored=await storage.get("session:session-1");assert.equal(stored.active,true);assert.notEqual(stored.token,"token-1");assert.equal(stored.pageFingerprint,null)});
test("first accepted snapshot binds exact origin and page fingerprint",async()=>{const m=await load("bind");const service=m.createObserverSessionService({storage:new MemoryStorage(),now:()=>2500,randomUUID:()=>"session-1",randomToken:()=>"token-1"});await service.start({allowedOrigin:"https://gumroad.com",ttlMs:600000});const result=await service.acceptSnapshot({sessionId:"session-1",sessionToken:"token-1",packet:packet()});assert.equal(result.ok,true);const current=await service.read({sessionId:"session-1",sessionToken:"token-1"});assert.equal(current.session.origin,"https://gumroad.com");assert.equal(current.session.pageFingerprint,"obsfp:abc12345");assert.equal(current.latest.page_title,"Edit product")});
test("changed fingerprint is rejected as stale after first bind",async()=>{const m=await load("stale");const service=m.createObserverSessionService({storage:new MemoryStorage(),now:()=>2500,randomUUID:()=>"session-1",randomToken:()=>"token-1"});await service.start({allowedOrigin:"https://gumroad.com",ttlMs:600000});assert.equal((await service.acceptSnapshot({sessionId:"session-1",sessionToken:"token-1",packet:packet()})).ok,true);assert.deepEqual(await service.acceptSnapshot({sessionId:"session-1",sessionToken:"token-1",packet:packet({page_fingerprint:"obsfp:changed",captured_at:new Date(2600).toISOString()})}),{ok:false,code:"STALE_PAGE"})});
test("wrong token and explicit stop both block further snapshots",async()=>{const m=await load("stop");let clock=2500;const service=m.createObserverSessionService({storage:new MemoryStorage(),now:()=>clock,randomUUID:()=>"session-1",randomToken:()=>"token-1"});await service.start({allowedOrigin:"https://gumroad.com",ttlMs:600000});assert.deepEqual(await service.acceptSnapshot({sessionId:"session-1",sessionToken:"wrong",packet:packet()}),{ok:false,code:"SESSION_INACTIVE"});assert.equal((await service.stop({sessionId:"session-1",sessionToken:"token-1"})).ok,true);clock=2600;assert.deepEqual(await service.acceptSnapshot({sessionId:"session-1",sessionToken:"token-1",packet:packet({captured_at:new Date(2600).toISOString()})}),{ok:false,code:"SESSION_INACTIVE"})});
test("screenshot consent is server-side and one-shot",async()=>{const m=await load("consent");const service=m.createObserverSessionService({storage:new MemoryStorage(),now:()=>2500,randomUUID:()=>"session-1",randomToken:()=>"token-1"});await service.start({allowedOrigin:"https://gumroad.com",ttlMs:600000});assert.equal((await service.grantScreenshot({sessionId:"session-1",sessionToken:"token-1"})).ok,true);assert.equal((await service.consumeScreenshot({sessionId:"session-1",sessionToken:"token-1"})).allowed,true);assert.deepEqual(await service.consumeScreenshot({sessionId:"session-1",sessionToken:"token-1"}),{allowed:false,code:"SCREENSHOT_CONSENT_REQUIRED"})});
