"use strict";
const test=require("node:test"); const assert=require("node:assert/strict"); const path=require("node:path"); const {pathToFileURL}=require("node:url");
const root=path.resolve(__dirname,".."); const url=pathToFileURL(path.join(root,"go-hub-artifact.js")).href; const ledgerUrl=pathToFileURL(path.join(root,"go-hub-evidence-ledger.js")).href;
const assembly={id:"a1",blueprintRef:"spec.md",integrationHeadSha:"head-a"}; const qc={status:"pass",checkedHeadSha:"head-a"};
const mergeGate={status:"MERGED_VERIFIED",assemblyId:"a1",sourceHeadSha:"head-a",pullRequestHeadSha:"head-a",ciHeadSha:"head-a",mergeSha:"main-a",mainSha:"main-a"};
test("build artifact binds digest and location to verified merged main source",async()=>{const {createBuildArtifact}=await import(`${url}?${Date.now()}`);const a=createBuildArtifact({id:"art1",kind:"web",assembly,assemblyQc:qc,mergeGate,digest:"sha256:1",location:"https://app.test",builtAt:"now"});assert.equal(a.assemblyHeadSha,"head-a");assert.equal(a.sourceHeadSha,"main-a");assert.equal(a.blueprintRef,"spec.md");assert.equal(a.status,"BUILT");assert.equal(Object.isFrozen(a),true);});
test("build rejects failed or stale QC and incomplete artifact identity",async()=>{const {createBuildArtifact}=await import(`${url}?${Date.now()}`);assert.throws(()=>createBuildArtifact({id:"art",kind:"web",assembly,assemblyQc:{...qc,status:"fail"},mergeGate,digest:"d",location:"x",builtAt:"now"}),/Assembly QC/);assert.throws(()=>createBuildArtifact({id:"art",kind:"web",assembly,assemblyQc:{...qc,checkedHeadSha:"old"},mergeGate,digest:"d",location:"x",builtAt:"now"}),/Assembly QC/);assert.throws(()=>createBuildArtifact({id:"art",kind:"web",assembly,assemblyQc:qc,mergeGate,digest:"",location:"x",builtAt:"now"}),/digest/);});
test("artifact inspection uses only evidence bound to the exact digest",async()=>{const {inspectArtifact}=await import(`${url}?${Date.now()}`);const artifact={id:"art1",digest:"d1"};const evidence=[{id:"load",scope:"artifact",claim:"artifact-loads",value:{digest:"d1"}},{id:"bind",scope:"artifact",claim:"source-binding-correct",value:{digest:"d1"}},{id:"old",scope:"artifact",claim:"artifact-loads",value:{digest:"old"}}];assert.deepEqual(inspectArtifact({artifact,evidence}).evidenceIds,["load","bind"]);assert.equal(inspectArtifact({artifact,evidence:evidence.slice(0,1)}).status,"fail");});
test("artifact evidence requires a digest value",async()=>{const {createEvidenceEntry}=await import(`${ledgerUrl}?${Date.now()}`);assert.throws(()=>createEvidenceEntry({id:"e",scope:"artifact",claim:"artifact-loads",kind:"probe",value:{}}),/digest/);});
