"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const path=require("node:path");const{pathToFileURL}=require("node:url");
const root=path.resolve(__dirname,"..");const modulePath=path.join(root,"go-hub-browser-observer.js");const moduleUrl=pathToFileURL(modulePath).href;
async function load(tag){assert.equal(fs.existsSync(modulePath),true,"GO Hub observer ingress is not implemented yet");return import(`${moduleUrl}?hub-observer=${tag}-${Date.now()}`)}
function packet(overrides={}){return{schema_version:"go-browser-observer-v1",session_id:"session-1",captured_at:new Date(2000).toISOString(),origin:"https://gumroad.com",sanitized_path:"/products/demo",page_title:"Edit product",viewport:{width:390,height:844},page_fingerprint:"obsfp:abc12345",visible_landmarks:[],visible_text_snippets:[],interactive_elements:[],fields:[{label:"Name",field_kind:"text",semantic:"title",safe_value_or_state:"Lost Era",confidence:"high",sensitivity:"safe",status:"SAFE_READ"}],redaction_report:{sensitive_blocked:0,unknown_redacted:0,hidden_omitted:0},optional_screenshot_ref:null,...overrides}}
function session(overrides={}){return{sessionId:"session-1",active:true,origin:"https://gumroad.com",expiresAt:60000,pageFingerprint:"obsfp:abc12345",screenshotConsent:false,...overrides}}
test("Hub accepts a fresh packet for the exact active session and fingerprint",async()=>{const hub=await load("valid");assert.deepEqual(hub.validateObserverPacket(packet(),session(),{now:2500}),{ok:true,code:null})});
test("Hub rejects wrong schema",async()=>{const hub=await load("schema");assert.deepEqual(hub.validateObserverPacket(packet({schema_version:"wrong"}),session(),{now:2500}),{ok:false,code:"SCHEMA_REJECTED"})});
test("Hub rejects inactive, missing, mismatched, and expired sessions",async()=>{const hub=await load("session");assert.deepEqual(hub.validateObserverPacket(packet(),null,{now:2500}),{ok:false,code:"SESSION_INACTIVE"});assert.deepEqual(hub.validateObserverPacket(packet(),session({active:false}),{now:2500}),{ok:false,code:"SESSION_INACTIVE"});assert.deepEqual(hub.validateObserverPacket(packet({session_id:"other"}),session(),{now:2500}),{ok:false,code:"SESSION_INACTIVE"});assert.deepEqual(hub.validateObserverPacket(packet(),session({expiresAt:2000}),{now:2500}),{ok:false,code:"SESSION_EXPIRED"})});
test("Hub rejects stale packets",async()=>{const hub=await load("stale");assert.deepEqual(hub.validateObserverPacket(packet({captured_at:new Date(1000).toISOString()}),session(),{now:40000,maxAgeMs:30000}),{ok:false,code:"STALE_PAGE"})});
test("Hub rejects fingerprint mismatch",async()=>{const hub=await load("fp");assert.deepEqual(hub.validateObserverPacket(packet({page_fingerprint:"obsfp:new"}),session(),{now:2500}),{ok:false,code:"STALE_PAGE"})});
test("Hub rejects non-Gumroad origin and unsanitized path",async()=>{const hub=await load("origin");assert.deepEqual(hub.validateObserverPacket(packet({origin:"https://evil.example"}),session(),{now:2500}),{ok:false,code:"HOST_BLOCKED"});assert.deepEqual(hub.validateObserverPacket(packet({sanitized_path:"/products/demo?token=secret"}),session(),{now:2500}),{ok:false,code:"SCHEMA_REJECTED"});assert.deepEqual(hub.validateObserverPacket(packet({sanitized_path:"/products/demo#frag"}),session(),{now:2500}),{ok:false,code:"SCHEMA_REJECTED"})});
test("Hub rejects sensitive or raw unknown fields",async()=>{const hub=await load("sensitive");assert.deepEqual(hub.validateObserverPacket(packet({fields:[{label:"Password",field_kind:"password",semantic:"unknown",safe_value_or_state:"secret",confidence:"high",sensitivity:"sensitive",status:"SAFE_READ"}]}),session(),{now:2500}),{ok:false,code:"SENSITIVE_CONTENT_BLOCKED"});assert.deepEqual(hub.validateObserverPacket(packet({fields:[{label:"Mystery",field_kind:"text",semantic:"unknown",safe_value_or_state:"raw-value",confidence:"low",sensitivity:"unknown",status:"FIELD_UNKNOWN_REDACTED"}]}),session(),{now:2500}),{ok:false,code:"SENSITIVE_CONTENT_BLOCKED"})});
test("Hub requires screenshot consent",async()=>{const hub=await load("shot");const withShot=packet({optional_screenshot_ref:"shot:1"});assert.deepEqual(hub.validateObserverPacket(withShot,session(),{now:2500}),{ok:false,code:"SCREENSHOT_CONSENT_REQUIRED"});assert.deepEqual(hub.validateObserverPacket(withShot,session({screenshotConsent:true}),{now:2500}),{ok:true,code:null})});
test("observer ingress has no Browser Run dependency or action API",async()=>{const hub=await load("boundary");const source=fs.readFileSync(modulePath,"utf8");assert.equal(source.includes("quickAction"),false);assert.equal(source.includes("BROWSER"),false);const forbidden=/click|type|fill|submit|publish|purchase|navigate|eval/i;assert.deepEqual(Object.keys(hub).filter(key=>forbidden.test(key)),[])});
